services:
    postgres:
        image: ankane/pgvector:v0.5.0
        platform: linux/amd64
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
